package com.it7890.model;

import java.util.Date;

public class SdkAlive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.id
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.packname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private String packname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.classname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.start_time
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.end_time
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.status
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.createtime
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.updatetime
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.createuid
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private Integer createuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_alive.createname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    private String createname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.id
     *
     * @return the value of sdk_alive.id
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.id
     *
     * @param id the value for sdk_alive.id
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.packname
     *
     * @return the value of sdk_alive.packname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public String getPackname() {
        return packname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.packname
     *
     * @param packname the value for sdk_alive.packname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setPackname(String packname) {
        this.packname = packname == null ? null : packname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.classname
     *
     * @return the value of sdk_alive.classname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.classname
     *
     * @param classname the value for sdk_alive.classname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.start_time
     *
     * @return the value of sdk_alive.start_time
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.start_time
     *
     * @param startTime the value for sdk_alive.start_time
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.end_time
     *
     * @return the value of sdk_alive.end_time
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.end_time
     *
     * @param endTime the value for sdk_alive.end_time
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.status
     *
     * @return the value of sdk_alive.status
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.status
     *
     * @param status the value for sdk_alive.status
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.createtime
     *
     * @return the value of sdk_alive.createtime
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.createtime
     *
     * @param createtime the value for sdk_alive.createtime
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.updatetime
     *
     * @return the value of sdk_alive.updatetime
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.updatetime
     *
     * @param updatetime the value for sdk_alive.updatetime
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.createuid
     *
     * @return the value of sdk_alive.createuid
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public Integer getCreateuid() {
        return createuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.createuid
     *
     * @param createuid the value for sdk_alive.createuid
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setCreateuid(Integer createuid) {
        this.createuid = createuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_alive.createname
     *
     * @return the value of sdk_alive.createname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public String getCreatename() {
        return createname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_alive.createname
     *
     * @param createname the value for sdk_alive.createname
     *
     * @mbg.generated Fri May 11 16:08:48 CST 2018
     */
    public void setCreatename(String createname) {
        this.createname = createname == null ? null : createname.trim();
    }
}